version: '3'

services:
  web:
    image: nginx:mainline-alpine
    container_name: 'webserver'
    ports:
      - "80:80"
    volumes: 
      - ./config:/etc/nginx/conf.d/
    links:
      - api
    networks: 
      - app-network
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      PORT: "7000"
    container_name: 'api'
    ports:
      - "7000:7000"
    expose:
      - "7000"
    networks: 
      - app-network
networks: 
  app-network:
    driver: bridge